trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: 'Build and Test'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
        mkdir -p $(Build.ArtifactStagingDirectory)
        cp -R build/* $(Build.ArtifactStagingDirectory)
      displayName: 'Install dependencies, build, and copy output'

    - script: |
        CI=true npm test
      displayName: 'Run tests'

    - script: |
        echo "Build and tests completed successfully"
      displayName: 'Post-build step'

    - script: |
        ls -la $(Build.ArtifactStagingDirectory)
      displayName: 'List build output'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: DockerBuildAndPush
  jobs:
  - job: DockerBuildAndPush
    displayName: 'Build and Push Docker Image'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerConnection'
        repository: 'myapp'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
      displayName: 'Build and Push Docker Image'
